### PR TITLE
Fix Date Parsing on Fitness Cron Job

### PR DESCRIPTION
**Pull request by vcai122**

### CODE REVIEW

**Review by tuneerroy — APPROVED** [review]
LGTM!

**Comment by judtinzhang** [comment]
Since we aren't sure of the format that they are logging, I think it might be worthwhile to try-catch parsing the datetime under both formats, and then only propagating the one that works into the rest of the code.

**Review by judtinzhang — COMMENTED** [review]
Comment above ^ lemme know what you guys think @tuneerroy @vcai122

**Comment by vcai122** [comment]
@judtinzhang yea i also thought of this. i think both could be good. alternatively would something like python-dateutil be overkill for this? python-dateutil can sort of guess the time from lots of formats

**Comment by judtinzhang** [comment]
@vcai122 oh wow that library looks really cool. I don't think it is overkill especially since we have no control on the format of that data day-to-day. I think thats a good idea :)

**Review by judtinzhang — APPROVED** [review]
Looks great! Thanks for doing this :)

**Pull request merged**
